version: '3.9'
name: ANGULAR-PROY-V1-SWTVAP-WEB-S2401
services:
    web:
        image: ANGULAR-PROY-V1-SWTVAP-WEB-S2401
        container_name: ANGULAR-PROY-V1-SWTVAP-WEB-S2401
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            #Deployment Proyect
            - "127.0.0.1:3002:3002"
            #Karma - npm run test
            - "127.0.0.1:9876:9876"
        volumes:
            - "C:\\Users\\Virtual\\Desktop\\Promsace\\Proyecto:/home/Proyects"
        tty: true
networks:
    default:
        name: nat

#Change route of folder local
#Example: C:\\Users\\Virtual\\Desktop\\Proyecto


#docker-compose up -d 
