export interface FormularioPagoInterface {
    store_id:number,
    name: string,
    email: string,
    celphone: string,
    document: string,
    document_type: string,
    country_phone_code: string,
    country_phone_id: number,
    country_id: number,
    deparment_id: number,
    province_id: number,
    district_id: number,
    message: string,
    error: string,
    first_name: string,
    last_name: string,
    comment: string,
    reference: string,
    address: string,
    check_save_to_pay_form: boolean,
    check_payment_method: number,
    check_delivery_type: boolean,
    payment_type_checked: boolean,
    payment_type: any,
}
