export interface OrderInterface {
    id :number,
	code: string,
	user_id:number,
	store_id:number,
	worker_id :number,
	user_name : string,
	user_first_name : string,
	user_last_name : string,
	user_document_type : string,
	user_document : string,
	user_email: string,
	user_celphone : string,
	user_code_celphone : string,
	payment_method :number,
	delivery_time: number,
	delivery_date: string,
	date: string,
    address: string,
    address_google_maps:string,
	optional_address: string,
	address_type : string,
	latitud : string,
	longitud : string,
	floor_number :number,
	type_bank :string,
	account_number :string,
	operation_number :string,
	comision: number,
	status :number,
	status_pay :number,
	order_programmer :number,
	order_programmer_date_time:string,
	collect :number,
	debt : number,
	description :string,
	comment :string,
	coverage_id :number,
	coverage_price :number,
	coverage_name :string,
	country_id :number,
	payment_card_id :number,
	country_department_id:number,
	country_district_id:number,
	country_province_id :number,
}
