export interface StoreInterface {
    stores_address: string,
    stores_celphone: string,
    stores_collect: string,
    stores_country_phone_code: string,
    stores_coverage: any,
    stores_delivery: string,
    stores_description:  string,
    stores_email: string,
    stores_facebook: string,
    stores_id: number,
    stores_image: string,
    stores_path: string,
    stores_image_url: string,
    stores_instagram:  string,
    stores_latitud: string,
    stores_longitud: string,
    stores_name: string,
    stores_address_referential:string,
    stores_address_type:string,
    stores_uri: string,
    stores_nickname:string,
    stores_whatsapp: string,
    store_customizers:string,
    stores_user_like: number,
    stores_user_follow: number,
    store_quantity_followers: number,
    store_quantity_likes: number,
    store_quantity_views: number,
    stores_despatch_time?:any,
    store_customizer_bootstrap:{
      scss_name:string,
      theme_color_primary:string,
      theme_color_secondary:string,
      theme_color_success:string,
      theme_color_info:string,
      theme_color_warning:string,
      theme_color_danger:string,
      theme_color_light:string,
      theme_color_light_text: string,
      theme_color_dark:string,
      theme_color_first : string,
      theme_color_first_text : string,
      theme_color_second : string,
      theme_color_second_text: string,
      theme_color_background: string,
      theme_color_background_text: string,
      grid_break_point_xs:string,
      grid_break_point_sm:string,
      grid_break_point_md:string,
      grid_break_point_lg:string,
      grid_break_point_xl:string,
      body_bg:string,
      body_color:string,
      font_size_base:string,
      line_height_base:string,
      font_url:string,
      font_family_san_serif:string
    }[],
    hours:any,
    payment_card:any,
    today:any,
    broadcasting:any,
    stores_facebook_button: any,
    categories:any,
    products:any,
    stores_deparments: {
      id: number,
      name: string,
      provinces: {
        id: number,
        name: string,
        districts: {
          id: number,
          name: string,
        }[]
      }[]
    }[];
}
