export interface UserInterface {
    type_user: string,
    name: string,
    email: string,
    celphone: string,
    document: string,
    document_type: string,
    country_phone_code: string,
    country_phone_id: number,
    country_id: number,
    deparment_id: number,
    province_id: number,
    district_id: number,
    message: string,
    error: string,
    token: string,
    password_confirmation: string,
    provider: string,
    image: string,
    first_name: string,
    last_name: string,
    comment: string,
    reference: string,
    address: string,
    check_save_to_pay_form: boolean,
    check_payment_method: number,
}
