export enum EcommerceWhiteEnum {
    PATH = '/',
    CART = '/cart',
    CHECKOUT = '/checkout',
    CHECKOUT_BILLING = '/checkout/billing',
    PRODUCTS = '/c/',
    POLITICS_AND_PRIVACY = '/politics-and-privacy',
    ABOUT_US = '/about-us',
    SHIPPING_METHODS = '/shipping-methods',
    PRODUCT_RETURN = '/product-return',
    CUSTOMER_SUPPORT = '/customer-support',
    CONTACT_US = '/contact-us',
    FREQUENTLY_ASKED_QUESTIONS = '/frequently-asked-questions',
    NOT_FOUND = '/not-found',
}
