export enum HomeEnum {
  FOOTER = 'FOOTER',
  FOOTER_COPYRIGHT = 'FOOTER_COPYRIGHT',
  FOOTER_COPYRIGHT_ES = 'FOOTER_COPYRIGHT_ES',
  FOOTER_COPYRIGHT_EN = 'FOOTER_COPYRIGHT_EN',
  FOOTER_MENU = 'FOOTER_MENU',
  FOOTER_TOP = 'FOOTER_TOP',
  FOOTER_NEWSLETTER_MESSAGE = 'FOOTER_NEWSLETTER_MESSAGE',
  FOOTER_CONTACTUS_MESSAGE = 'FOOTER_CONTACTUS_MESSAGE'
}
