export enum ServiceWhiteEnum {
  LOGIN = 'api/auth/login',
  REFRESH_TOKEN = 'api/auth/refresh-token',
  LOGOUT = 'api/auth/logout',
  W_PARAMETERS = 'api/w-parameters',
  W_PARAMETERS_BY_CODES = 'api/w-parameters/code',
  W_CATALOGS = 'api/w-catalogs',
  W_CATALOGS_BY_LANG = 'api/w-catalogs/lang',
  W_CONTACTS = 'api/w-contacts',
  W_PRODUCTS = 'api/w-products',
  W_REVIEWS = 'api/w-reviews',
  W_COMMENTS = 'api/w-comments',
  W_ANALYTICS = 'api/w-analytics',
  W_ORDERS = 'api/w-orders',
  W_NEWSLETTER_SUBSCRIPTIONS = 'api/w-newsletter-subscriptions',
  ASSETS_I18N_ES = 'assets/i18n/es.json',
  ASSETS_I18N_EB = 'assets/i18n/en.json',
}
